#!/bin/bash

main_loop()
{
  checkfile || log "No access to DB file"

  local -A choices
  local -i choice_nr
  local choice PS3

  choices=(
    [TODO: Add a record]=uiRecordAdd                 # 1. TODO
    [Delete a record]=uiRecordDelete
    [TODO: Search by name]=uiRecordSearch            # 3. TODO
    [TODO: Update name]=uiRecordUpdateName           # 4. TODO
    [TODO: Update amount]=uiRecordUpdateAmt          # 5. TODO
    [TODO: List records (summery)]=uiRecordListTotal # 6. TODO
    [TODO: List records (sorted)]=uiRecordListSort   # 7. TODO
    [exit]=exit
  )

  printf -v PS3 "\x1b[32;1m%s\x1b[m: " "Select an action"

  select choice in "${!choices[@]}"; do
    if
      (( choice_nr=REPLY, choice_nr == 0 || choice_nr > ${#choices[@]} ))
    then
      echo "Invalid choice" >&2
      continue

    else
      "${choices[$choice]}"

    fi
  done
}

lib=$(dirname "$(realpath "${BASH_SOURCE[0]}") ")/lib
source "${lib}/db_check"
source "${lib}/add_rec"
source "${lib}/del_rec"
main_loop "$@"
