#!/bin/bash

main_loop()
{
  checkfile || log "No access to DB file"

  local -a choices
  local -i choice_nr
  local choice PS3 OFS IFS; OFS=$IFS IFS=$'\n'

  choices=(
    "TODO: Add a record"
    "Delete a record"
    "TODO: Search by name"
    "TODO: Update name"
    "TODO: Update amount"
    "TODO: List records (summery)"
    "TODO: List records (sorted)"
    "exit"
  )

  printf -v PS3 "\x1b[32;1m%s\x1b[m: " "Select an action"
  select choice in "${choices[@]}"; do
    if
      (( choice_nr=REPLY, choice_nr == 0 || choice_nr > ${#choices[@]} ))
    then
      echo "Invalid choice" >&2
      continue

    else
      case "$choice" in
        "TODO: Add a record")
          ;;
        "Delete a record")
          uiRecordDelete
          ;;
        "TODO: Search by name")
          ;;
        "TODO: Update name")
          ;;
        "TODO: Update amount")
          ;;
        "TODO: List records (summery)")
          ;;
        "TODO: List records (sorted)")
          ;;
        "exit")
          exit
          ;;
        *)
          log "invalid choice allowed" && exit 1
          ;;
      esac
    fi
  done
}

lib=$(dirname "$(realpath "${BASH_SOURCE[0]}") ")/lib
source "${lib}/db_check"
source "${lib}/add_rec"
source "${lib}/del_rec"
main_loop "$@"
